edit entities
momentum-mod/lumper pull request #29
Opened 2023-08-19 14:21 UTC by BIRD311

2023-10-21 16:37 UTC, tsa96 requested changes

2023-10-21 16:37 UTC, tsa96 commented on src/Lumper.UI/ViewModels/Bsp/BspNodeBase.cs
> +using System.Collections.Generic;
Needed?

2023-10-28 20:20 UTC, tsa96 approved these changes

2023-10-30 05:11 UTC, Panzerhandschuh approved these changes

2023-11-05 16:58 UTC, merged